# Generated by Django 3.2 on 2023-03-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='linitem_total',
            new_name='lineitem_total',
        ),
    ]
