# Generated by Django 3.2 on 2023-03-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20230324_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='strip_pid',
            new_name='stripe_pid',
        ),
    ]
